language: python
python:
  - "3.5"
  - "3.5-dev"
  - "3.6-dev"
  - "nightly"
install:
  - pip install numpy pyyaml
  - pip install coverage coveralls # for CI
script:
  - python ./examples/generate_images.py
  - coverage run --source=blockschaltbilder setup.py test
after_success: coveralls
